### PR TITLE
Cleaned up routing of the handoffs

### PR DESCRIPTION
**Pull request by ato1120**
Handoffs had some small pixels adjustments to be made to fix alignment. Nothing new in the code, all just changes to the routing. Included an old photo from master and new photo from the PR below. Nothing to actually test, but can play around to make sure they look ok. 

screen shot 2015-01-11 at 8 06 15 pm

screen shot 2015-01-11 at 8 05 59 pm

### CODE REVIEW

**Comment by negarrahmati** [comment]
I think there is still an alignment issue. Attached a picture:
image

**Comment by ato1120** [comment]
Can you describe how you found that? Was it from loading an old team? I think any old teams have cached information about the handoffs that you can fix by moving them around.

**Comment by ato1120** [comment]
*Cached on events and handoffs. So even drawing a handoff on an old team will be wrong at first because it is reading incorrect json information.

**Comment by ato1120** [comment]
Ok, I fixed it! Something up with the way the first value for x is stored when an event is created.

**Comment by negarrahmati** [comment]
Great! Merged.

**Pull request merged**
