### PR TITLE
Can move members and folders into other folders

### LINKED ISSUE #257: Entry manager broke member invite links and uniqs for duplicated teams
When the team is duplicated, the urls and uniqs in the member popovers show the info from the original team (i.e. the team that was duplicated). I had fixed this and had it working when I resolved the duplicating issues in PR #233 but then when the "entry manager" was added (I think when the folders were introduced) it broke my fixes. If you look at the flashTeamsJSON in the console, it looks like my fixes are still there but now the member data is apparently stored in "_member_data" and "members" -- which include different information for duplicated team. Specifically, the "_member_data" has the incorrect information and the "members" data has the correct info. See screenshot below.

I tried fixing this but couldn't get it to work. @ofagbemi is this something you can fix? You might need to update the createDupTeamStatus function i created in the flash teams controller. Also, is it possible to only save the member info in one place? otherwise this will be extremely difficult to maintain...

image

### PR DESCRIPTION
**Pull request by ofagbemi**
Fixes #257, #254

screen shot 2015-02-21 at 12 18 01 am

screen shot 2015-02-21 at 12 18 30 am

screen shot 2015-02-21 at 12 18 39 am

You can also drag into breadcrumbs

screen shot 2015-02-21 at 12 32 11 am

### CODE REVIEW

**Comment by ato1120** [comment]
Awesome! Is there any way you could add drag to reorder to this as well? (So in your example photos, drag 'Cool' to below both of the 'New role" members)

I also noticed a small bug. The "Add Folder" button is still active and available in author view when the team is live. I haven't tried clicking on it for fear of breaking things, but do you think you could pull that fix into this branch as well? If not we can do another branch for that.

**Comment by ofagbemi** [comment]
Sorry I took so long to get back to you on this. Do you know off hand how I
can check if the team is live?

I can probably get to dragging to reorder by the end of the week, but I
wanted to ask—do you think that'll be necessary? Do you feel that people
try to drag things out of order often? I feel like it might be better to
just have a few sorting options, maybe alphabetically and by creation time.

**Comment by ofagbemi** [comment]
There is an “in_progress” variable which tells you if the team is in progress (this var might also help you fix the handoff/collab icons in runtime bug). 

I think sorting options could work. I could imagine times where you might want to custom sort the roles but I don’t think it is a super high priority. One thing to keep in mind when sorting though is the order of folders and roles. Perhaps the folders should always be on the top (or bottom)? I just feel like it might be weird to have folders and roles all mixed up. Open to other thoughts on this though! 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Comment by ofagbemi** [comment]
Okay, fixed the live team bug. Right now the folders are above the members.

**Comment by ofagbemi** [comment]
Should the add member button also be disabled? I'm probably going to head
to bed pretty soon, but I can get to it in about 15 or so hours I think.

**Comment by ofagbemi** [comment]
Yep, the add member button should also be disabled! 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Comment by dretelny** [comment]
This doesn't work. The role links are still wrong for duplicated teams (see first screenshot) and now the hiring portal is broken (i.e. when you click on the hire button it now raises an error - see second screenshot). 

Incorrect role links (this is team 32 but the links are from team 31, which was the team i originally duplicated): 

image

Hiring portal (relies on members from flashTeamsJSON): 
image

**Comment by ofagbemi** [comment]
Sorry, I made a bunch of fixes / pushed pretty recently. Could you try
pulling again?

**Comment by dretelny** [comment]
One more bug: 

Now the google drive upload links don’t show up in runtime (only the collaboration and handoff icons should disappear in runtime): 

image

**Comment by dretelny** [comment]
I am heading into a meeting and need to merging this since some of the updates are pretty critical. Can you make future changes in a new branch? I think the three things left are: 

1) fixing the folder dragging (which was overwritten when I merged master into your branch); 

2) the add members field is still active in runtime mode (i.e. when the team is in progress)[see screenshot below]; 

3) you can't sort members / move them around in the list (as previously discussed)

Screenshot of active "add new role" field when team is in progress: 

image

**Comment by ofagbemi** [comment]
Really sorry, I got caught up in something else and forgot to commit!

Added the folder dragging now. I'll just do the add members field and
sorting stuff in a different PR. You can merge that same branch again.

**Comment by dretelny** [comment]
Ok!! Will do. Thanks! Quick question, this update breaks all previous teams. There is no way to fix that, right? 
It’s probably not worth the effort but just want to double check

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Comment by dretelny** [comment]
Also, the dragging folders doesn’t work quite right. If you drag a folder into another folder it only appears inside the folder after you refresh the page

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Comment by ofagbemi** [comment]
Sorry, I actually created a pull request here
<https://github.com/StanfordHCI/foundry/pull/259>.

I think it might work with old teams, actually. I just sent in a fix that
looks like it works with some old teams now in that PR ^.

**Comment by dretelny** [comment]
Ok, the dragged changes don’t appear until you refresh the page. Is that easy to fix? 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Pull request merged**
