### PR TITLE
At documentation2

### PR DESCRIPTION
**Pull request by ato1120**
Splitting events.js into 3 files: events.js, eventDraw.js, eventDetails.js

eventDraw.js has the function eventDraw() and all of its sub-functions (e.g., drawMemberTabs(), drawMainRect(), etc.)

eventDetails has the large piece of data that holds all of the task drawing details that Jare wrote. It's really once gigantic function. 

Also deleted certain functions such as ones pertaining to drawing things that we no longer draw (member circles, dragbars, gdrive link, and duration text). Changed member circle functions we still use to "member tab" functions in name. 

Removed all overlay functions. If you recall, we used to have an overlay div that turned on and off so you could draw or not draw events. We don't do this anymore so those are gone. 

You will want to do the full stack of testing. Draw a new team with events and people. Check to make sure everything rends on worker and author mode. Make sure everything renders after starting the team, starting the task, pausing a task, going late on a task, and completing a task. Make sure refresh works at all of those stages. 

Look out for console errors that are new and look closely at the tasks to make sure nothing is missing. 

It is important to note that these files are still not well commented. There is a brief description at the top, but this is such a large structural change that it needs to happen ASAP.

### CODE REVIEW

**Comment by dretelny** [comment]
Didn't make it very far before encountering a blocking bug :( 

Specifically, I created a new team and then dragged to create a new event at which point an error came up in the console and the event didn't draw properly: 

image

**Comment by ato1120** [comment]
Sorry about that! I saw that bug, fixed it, but didn't push the change. Is it ok on your end now?

**Comment by dretelny** [comment]
The google drive button in the sidebar as well as the google drive links on each of the events don't work. You can't click the button and if you click on the upload icons on the events you get the following error: 

image

Also, if you click on the direct link in the complete task modal for the google drive folder, it takes you to an undefined link, which brings up the following error screen: 

image

**Comment by dretelny** [comment]
Merging!

**Pull request merged**
