### PR TITLE
Dr training design

### PR DESCRIPTION
**Pull request by dretelny**
I redesigned the on demand hiring training/on boarding so that the design is more visually appealing and matches the hiring portal. When reviewing, check that:

1) all of the form fields (on the launch training and registration form page) work ok (I used some JavaScript to hide the modals from the html when they are not active because it was causing problems for me)
2) the modals load properly
3) the alignment of the content on the modals and buttons is ok 

Make sure there are no other styling issues I missed. Hopefully this is an improvement from what was there :)

### CODE REVIEW

**Comment by dretelny** [comment]
I forgot to mention that you access this at localhost/workers/register :)

**Comment by ato1120** [comment]
I don't think we want the checklist on page 2/10 to be centered. It is really tough to read that way.

**Comment by ato1120** [comment]
I think for the most part I disagree with the redesign. While everything is 'prettier' it is all a lot harder to read now. Would love to get a second opinion from someone. I think the font is a little tough to parse and all of the lists really need to be left-aligned.

**Comment by ato1120** [comment]
I like the landing page with the new header, but even all of that info should be left-aligned. And the new font/font-color is hard to read.

**Comment by dretelny** [comment]
The font and alignment is easy to change. Is that the only issue?

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Pull request merged**
