### PR TITLE
[NOT COMPLETED]Async update

### PR DESCRIPTION
**Pull request by ArtyomTs**
Do not merge please.

### CODE REVIEW

**Comment by dretelny** [comment]
1) The timers on the tasks do not appear to work. Specifically: a) when you click start on a task, the timer never changes on the task on the workflow (it stays at 2 hours): 
image

b) When you click on the task, the remaining time (which is based off the timer) says "NaN:NaN" insteaed of the time remaining: 
image

2) I couldn't test any of the updating features in the multiple views because none of the emails appear to be working. This might be due to the fact that the none of the add ons have been added to heroku. It might make sense to push this to our foundry-app-dev heroku, which has all of the necessary add ons.

**Comment by dretelny** [comment]
You can't add any members to the team. When you enter a member name and then click enter it clears the name and raises an error in the console. See screenshot below:

image

**Comment by ArtyomTs** [comment]
Members are fixed.

**Comment by dretelny** [comment]
Merging this!

**Pull request merged**
