### PR TITLE
Dr dup team fix

### PR DESCRIPTION
**Pull request by dretelny**
I THINK this pull request fixes most of the issues that occur when you try to duplicate a team. Below is a summary of the changes I made: 

1) When you duplicate a team that has members on it, the member link is automatically updated (i.e. it is not the same link as the original source team) 

2) A new google drive folder is created. This was not easy to do so please make sure you test it robustly to make sure I didn't mess anything up. Note that unlike before, the google drive project folder and folders for each of the tasks are now created when you click on the start button. Previously, the project folder was created when the first task was added to the timeline but that was quite problematic when it came to creating a new project folder post-duplication (and I don't think we really need the folder until the team starts). 

3) The google drive button used to show up before the team was started but now I changed it so that it only appears once that team is in progress (since that's when the project folder is created). Therefore, it should be hidden whenever the team is not in progress (it should happen automatically when you click on the start button but you need to refresh after you click on the end button) 

4) I think I fixed the issue that was preventing the google drive button from sometimes not working. I now call the googleDriveLink() function when the team is started. Previously it was only called in loadData. 

When testing, do the following: 
1) Create a team, add members and tasks (with members assigned) 
2) Invite members, start the team and visit the workflow using the member link (before and/or after you start the team)
3) Click on the google drive button. Make sure it opens the project folder
4) Click on the task upload buttons. Make sure they open the right folder. 
5) Duplicate that team (when you duplicate it, make sure everything looks ok). Feel free to edit / make changes to your team, although you don't have to (it shouldn't make a difference)
6) Invite members to your team and visit the workflow using the member link. After you do that, check that the member link from the original team still works (it should) 
7) Click on the google drive button. Make sure it opens the project folder
8) Click on the task upload buttons. Make sure they open the right folder. 
9) As you are doing this, make sure the google drive button in the sidebar appears correctly 

If you really want to test this in depth, you might also consider testing the emails (i.e. notifications when the task is delayed, etc.). I tested them and they worked. My branch is currently on foundry-app-dev if you want to test the emails there! 

Feel free to test whatever else you think is relevant but this is all I can think of! Thanks!

### CODE REVIEW

**Comment by ato1120** [comment]
The Google Drive Button never seems to load when I first click 'Start Team' although the window does pop down to give room for it. It appears after refresh. 
screen shot 2015-02-11 at 11 18 15 pm

**Comment by ato1120** [comment]
Was this PR also supposed to address issue #171? I think we had previously determined that this was most frequent on duplicated teams. I am still seeing that behavior. 

Roughly: I create a team, add and delete some events in random order (so there are id gaps) and then duplicate. If I add new events to the duplicated team, I can accidentally create an event with a previously used id.

**Comment by ato1120** [comment]
Everything else looks great!! Nice work!!!

**Comment by dretelny** [comment]
I just changed the google drive button since it was a little glitchy with new teams. For now, in author runtime it should always be correct (not showing when team hasn't started / not in progress and showing when team has started). In worker view, it will always show up even if the team hasn't started (and the project folder hasn't been created). This is less of an issue since typically the team has started when the worker has been invited. I can fix this in a later PR. 

As far as the duplicate ID issue goes, I just played around with it and it happens with non-duplicated teams too. Basically if you erase a task and then refresh the page and create another task, it might take the last ID which would then mess up the ID with that task. This happens because the event_counter variable goes down and the has a high chance of matching the ID of an existing task. This is something we should fix in a different PR as it appears to effect all teams. Perhaps one solution would be to give tasks a randomly generated ID (I think this is what Jare had suggested too). 

Anyway, if those were your only comments, then I would go ahead and merge it :) 

Let me know. Thanks!

**Pull request merged**
