### PR TITLE
At int drag del

### LINKED ISSUE #120: Handoffs do not block Event Dragging
Currently, we prevent handoffs from being drawn if task 2 begins before task 1 ends. 

However, you can create a 'good handoff' and then drag task 2 backwards behind the start of task 1! Presumably, we want to block this.

screen shot 2014-11-23 at 3 11 38 pm

### PR DESCRIPTION
**Pull request by ato1120**
Should close #120 

When an event is dragged out of range for a collaboration or handoff, the interaction slowly fades out and then is deleted. 

The reason we are doing this and not an alert dialog is that when you do an alert dialog, the drag doesn't stop and the event drags all over the screen when you close the alert. This is more elegant. 

Part of the review is to make sure this semantically makes sense for a user. If they drag the event out of range the interaction goes away and doesn't come back if you drag back into range. 

Just draw lots of events, collabs, and handoffs. Make sure the definition of "out of range" seems correct, things are actually deleting, and that they don't come back after refresh or anything else.

### CODE REVIEW

**Comment by negarrahmati** [comment]
I am wondering if we should have the handoffs appear again after the event is dragged back in range. It might get irritating to have to redraw the handoff when ever an event goes out of range. What do you think?

**Comment by dretelny** [comment]
Let's discuss this in the code meeting?

**Comment by ato1120** [comment]
Finally updated this! I made a couple of new helper functions that make the code for a lot of handoff items a lot cleaner. So you will want to test that all normal things (drawing, deleting, redrawing, 'good' dragging) all work normally. 

If you drag an event out of range (event 1 ends after event 2 begins, dragging either event 1 or 2), you should get an alert explaining that you did something wrong, and the even should snap back. 
Also want to make sure that the event is in the right place after refresh, etc. 

Could also use feedback on the alert dialog. I don't like my phrasing. You want it to make sense for dragging event 1 or event 2.

**Comment by negarrahmati** [comment]
I tried to drag an event. It worked the first time but this is what I saw the second time:
image

I drew a collaboration and dragged the event but it just disappeared. It didn't show any alerts.

**Comment by ato1120** [comment]
Is this with a new team or old team? I'm trying to recreate right now and I can't.

**Comment by ato1120** [comment]
*Just for the handoffs, I realized I forgot to address the collaborations, sorry about that!

**Comment by negarrahmati** [comment]
This is a new team. I also had to merge the master first. Does that make a difference?

**Comment by ato1120** [comment]
Yeah, it looks like it did. =( I just pulled that change. I don't know why though... I'll look into it soon.

**Comment by ato1120** [comment]
Added the collaboration part. Should also have fixed the other bug?

**Comment by negarrahmati** [comment]
Thanks Alexandra. This is working perfectly. 
Can we change the wording a little bit before merging this? I feel like upstream and downstream might get a bit confusing.
One suggestion is:
Sorry! "event title 1" cannot start before "event title 2" ends.

What do you think?

**Comment by ato1120** [comment]
Done! Let me know how it looks. Changed for both collab and handoff.

**Comment by negarrahmati** [comment]
I see: "task1 and task 2 the must overlap..."
Could you get rid of the extra "the"?
 
The handoffs message is fine. :)

**Comment by ato1120** [comment]
Sorry, done!

**Pull request merged**
