### PR TITLE
notification emails

### PR DESCRIPTION
**Pull request by negarrahmati**
In order to test the emails:
1. The following doc briefly explains hor the emails work. The first 4 emails explained here must work. https://docs.google.com/document/d/19eShQ_Il17CyE0hA3NqkZQJk6vIduWZI04smI8ASmQ8/edit.

1.5. rake db:reset and rake db:migrate to delete all existing/running teams.

2. Create a team. Add the dri and members. Don't invite all the members. Draw the handoffs. 

3.  open a new command line. 
4. Start team. Wait until the first task is delayed. Right after it is delayed, type this command in the command line to run the email script:
rake notification:email_delayed_task

You should see an email sent to the dri of the delayed task in the command line. There is a link in the email that asks the dri to estimate the delay. Click on it and estimate the delay. Another email is sent out to the members of the dependent tasks explaining that a task is delayed and will be finished in X minutes.

4. Finish the delayed task. An email is sent out to the members of dependent tasks explaining that the delayed task is now finished.

5. start another task. Let it be delayed. Wait for 20 seconds and then run the command  "ake notification:email_delayed_task" in another command line. You should see the following email sent out to members of remaining tasks in the command line:

"Unfortunately, <%= @event_name %> by <%= @dri_role %> is not finished on time. We will notify you when the delayed task is finished or when we receive an estimation of the delay from <%= @dri_role %>. If you are in contact with <%= @dri_role %>, you might ask them to check their email so we can know when the task will be complete."

Note: make sure not to invite all members of the team. 

Important note: before pushing to heroku, change call_period variable in lib/tasks/scheduler.rake to 600 (real time).

### CODE REVIEW

**Comment by dretelny** [comment]
What's the status of this? why did you close it? @negarrahmati

**Comment by negarrahmati** [comment]
Because I want to submit another one. No worries, I have all your comments.

**Comment by dretelny** [comment]
ok, just checking :) 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Comment by negarrahmati** [comment]
The notifications are back. More robust this time. 

I added EMAIL_PERIOD to the config vars on heroku. I will send the updated local config file as soon as the branch is merged.

This branch is up on foundry-app-dev.heroku.com. Instructions to test on heroku:
1. Create a new team with two separate task threads. Invite all members except one. 
2. Assign workers to tasks. 
3. Start the team. After a task is delayed (wait for 10 minutes),  the members of the task should get an email with a link asking about the delay estimation. This email is sent to the DRI and all members are CCed. 
4. click on the link and estimate the delay. Members of the remaining task should get an email with the delay estimation.
5. Complete the task. Members of the dependent tasks should get an email indicating that the delayed task is finished. 
6. Start another task and wait for 20 minutes after it is delayed. Members of the dependent tasks should get an email that the task is delayed and they will be notified when we have an estimation of the delay.
7. replace a member and do the above steps again.

**Comment by dretelny** [comment]
Merging!

**Pull request merged**
