### PR TITLE
At handoff colors

### PR DESCRIPTION
**Pull request by ato1120**
This Pull Request:
-Changed all of the handoffs to gray
-Changed the tone of gray of the collaborations
-Adjusted the rendering of collaborations so they line up correctly
-Put an onhover for handoffs and collabs to put at full opacity (easier to see routes, easier to see is clickable)

To test, just create teams with various handoffs and see if it is clear where they are going. Try to make 'realistic' teams and not teams that unrealistically make the handoffs confusing. 

Note: Any old teams made with colorful handoffs will still be colorful. However, they should now still toggle opacity. If you want to test good teams, it might be a good idea to delete those colorful handoffs and redraw them in gray. 

Second Note: I am considering adding a color picker with other shades of gray, but would rather not if it seems redudant.

### CODE REVIEW

**Comment by negarrahmati** [comment]
This looks great Alexandra!

Here are my suggestions:
- The color of 3 overlapped handoffs is very close to the color of an  onhover handoff. Can we make the onhover handoff a bit darker?
- If we have a handoff to a task far on the right side of the timeline in a way that we have to scroll to the right to see the task, it gets very hard to keep the handoff bolded. I am wondering if it makes more sense to keep the handoff bolded if the user clicks on it. This way we can figure out the dependencies even if we need to scroll to the right or left on the timeline.

Let me know what you think! :]

Plus, can some one else take a look at this branch besides me? I think it is good to have a second opinion on this.  @dretelny

**Comment by ato1120** [comment]
Sounds good! I should be able to play around with this later today. Do you think a totally different color would be better? Like blue? For hover and for click? 

Let me know!

**Comment by ato1120** [comment]
Ok, so now handoffs turns higher opacity and blue on hover. In worker mode, all handoffs coming into and going out of a workers tasks are highlighted yellow regularly and also highlight blue on hover. 

I don't have the clicking working, that might take a lot longer.

**Comment by negarrahmati** [comment]
Great! Thanks Alexandra!
What do you think about demoing this quickly in our meeting today so that
we can know other's opinion about it before merging it?

**Comment by ato1120** [comment]
I showed the PR to Michael and Daniela and they are pleased with how it looks. As long as everything is working, you should be all set!

**Comment by negarrahmati** [comment]
Great! I will double check and merge it.

**Pull request merged**
