### PR TITLE
Dr hiring redesign

### PR DESCRIPTION
**Pull request by dretelny**
Completely redesigned the front-end of the hiring panel. The functionality is all the same but we need to make sure that nothing broke as I was updating the design since I changed the structure of the code quite a bit. 

Recall that the hiring portal and panels can be accessed in a few places [YOU MUST BE LOGGED IN AS AN AUTHOR]: 
P1) by clicking on the "panels" link in the hiring panel sidebar (i.e. click on the "hire button" on the task modal and then click on the "panel" link on the sidebar). The direct url for this is: http://localhost:3000/flash_teams/:id/:event_id/panels (for example: http://localhost:3000/flash_teams/1/0/panels)

P2) via the workers controller: localhost:3000/workers/index (this lets you access/edit the panels outside of the scope of any specific project or task)

P3) In a right sidebar next to all 3 of the hiring email templates [you can only filter in this view -- if you filter or select emails, they should automatically populate in the 'to' field of the email]

Ability to add workers to panel, which has separate views for requesters/PC and workers:
A1) As a requester, you can add a new worker to the panel by clicking on the "Add Worker" link on either of the two views listed above.

A2) As a worker, you can register for the panel via the following url: localhost:3000/workers/register

There are several tasks you should try when testing: 
1) Add workers to the panel via all three views (#P1, #P2, and #A2) --> make sure you are redirected to either the previous page you came from (showing the panel) when you add a new worker from views #P1 and #P2 or a "success" page when you register as a worker (i.e. view #A2). All fields in the form except for the additional information field are required in order to submit the form.

2) Edit workers in both views (#P1 and #P2). Make sure the worker info updates in the table

3) Try filtering the workers by panel type (i.e. via the dropdown) or by selecting workers by clicking the checkboxes in the table in the THREE PANEL VIEWS [#P1, #P2, #P3]

4) Try deleting workers. Make sure they delete in the table

### CODE REVIEW

**Comment by ato1120** [comment]
I'm getting to this rather slowly. A pretty shallow comment is that it's odd that you can click and highlight the headers "Hiring Emails" and "View Other Tasks" since they don't take you anywhere new. Could you disable that?

**Comment by ato1120** [comment]
Relatedly, I wish that the sub-headers for the task type and email type would highlight instead.

**Comment by dretelny** [comment]
Yes, that's a good point. If that's the only issue than merge it and I'll create another branch.

**Comment by ato1120** [comment]
The "Select All Emails" button on the filter (P3) has a bit of a confusing meaning semantically. I think you would want this to force all of the panel workers to be checkbox selected. Consider the case where you have 20 workers, but you only want 18 of them. Select all should check each checkbox so the user can then uncheck the correct ones.

**Comment by ato1120** [comment]
If an email is too long, the panel on P3 runs off the edge of the page so you can't access the checkboxes.
screen shot 2015-01-11 at 1 28 50 pm

**Comment by ato1120** [comment]
Something's a bit off with the panel rendering. Photo 1 is when I open the page. Photo 2 is when I click the 'x' on the panel and close it. Photo 3 is when I click 'View Panels"

screen shot 2015-01-11 at 1 33 19 pm

screen shot 2015-01-11 at 1 33 29 pm

screen shot 2015-01-11 at 1 33 35 pm

**Pull request merged**
