### PR TITLE
Event redesign

### PR DESCRIPTION
**Pull request by ofagbemi**
Implementation of the redesigned event prototype I sent out earlier:

screen shot 2015-01-10 at 2 13 57 am

I threw in some events at various lengths. Note that once the event gets down to an hour, the icon next to the number of members disappears.

The layout breaks down on events shorter than 1 hour:

screen shot 2015-01-10 at 2 19 02 am

I'm still thinking about a way to mitigate this.

### CODE REVIEW

**Comment by mbernst** [comment]
Drop the clock icon with super short events? The people will be visible with the under-tabs, and it will probably only ever say 30min (the only <1hr time), which would fit.

**Comment by ofagbemi** [comment]
Looks okay at 45, at 30 the title disappears completely:

screen shot 2015-01-10 at 3 37 36 am

screen shot 2015-01-10 at 3 38 53 am

I'm going to try doing that and shrinking + centering the icons.

**Comment by ofagbemi** [comment]
Here's the look so far

screen shot 2015-01-10 at 5 19 00 am

I think I'm going to try branching from here tomorrow and work out another idea and see if I can get something a little better.

**Comment by ato1120** [comment]
A couple comments:
-I'm a little concerned because with some of the shorter events, there is almost no place where you can click to edit the events on the modal. Is it possible to have the modal open when you click on the title and the time? (Right now you get the text edit cursor hover)
-I think the members icon can be a little larger. As of right now it is really hard to see what it is unless you look really closely. Or rather than larger, it just needs to be an icon that works well for that size.
-Can you confirm that all of the appropriate json elements and globals have been changed? I'm seeing some errors with the rendering of the collabs and handoffs. Those may need to be fixed (I could do that), but if I recall, last time they were re-done they were using globals and values from the event json that made it so they would not need to be re-written if the event proportions changed. Specifically, I'm getting a "Cannot read property 'x' of undefined" when trying to draw some new collabs.
-Finally, I don't know if the upload icon is firing the right thing. Check out the master branch. When I click upload there, it opens an alert that says "Team must be running to upload" and I don't get that on your branch.

**Comment by ofagbemi** [comment]
Got everything except for the handoffs problems now

[image: Inline image 1]

Changed the group icon to this and made it a tiny bit bigger.

I'll look into the handoffs issue. I'm not getting any errors with minimal
testing, but I'll look over the code and try and test it a little more very
soon.

**Comment by ofagbemi** [comment]
Oh, okay, sorry, I misread the specific error. It was an issue with the
collaborations. Fixed it now! I just forgot to set the groupNum attribute
on the collab button.

**Comment by ato1120** [comment]
Very nicely done!!

**Comment by ofagbemi** [comment]
Really fantastic work! I just merged this, so everyone coding can pull the
event redesign now!



Alexandra To
---------------------------------------------------------------------
B.S. '14, M.S. '15 Candidate in Symbolic Systems: Human-Computer
Interaction (HCI)
Minor in Asian American Studies
Stanford University
Residential Computer Consultant (RCC) - Rains Z
BOSP Head Student Advisor

**Comment by ofagbemi** [comment]
Hooray!

**Comment by ofagbemi** [comment]
Awesome! Nice job, Jare. Quick question. What was the verdict with the event colors? Are they pink by default now? 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Comment by ofagbemi** [comment]
Also, the events don’t appear to change colors once they are in progress, completed, etc. Alexandra, were you aware of this? 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Comment by ofagbemi** [comment]
Thanks! To Daniela, super sorry, I totally forgot to email you before I
went to bedーI wanted to sync up with you again about the colors just to
make sure everything was alright. I'm going to go back and adjust them this
afternoon and hopefully I'll have something ready for you guys before your
lunch time.

On Monday, January 12, 2015, Daniela Retelny <dretelny@stanford.edu> wrote:

> Also, the events don’t appear to change colors once they are in progress,
> completed, etc. Alexandra, were you aware of this?
>
> *Daniela Retelny*
> Stanford University
> Department of Management Science and Engineering
> (914) 450-2033
> dretelny@stanford.edu
> <javascript:_e(%7B%7D,'cvml','dretelny@stanford.edu');>
> www.danielaretelny.com
>
> On Jan 11, 2015, at 12:17 PM, Michael Bernstein <msb@cs.stanford.edu
> <javascript:_e(%7B%7D,'cvml','msb@cs.stanford.edu');>> wrote:
>
> Hooray!
>
> On Sun, Jan 11, 2015 at 12:16 PM, Alexandra To <ato1120@stanford.edu
> <javascript:_e(%7B%7D,'cvml','ato1120@stanford.edu');>> wrote:
>
>> Really fantastic work! I just merged this, so everyone coding can pull
>> the event redesign now!
>>
>>
>>
>> Alexandra To
>> ---------------------------------------------------------------------
>> B.S. '14, M.S. '15 Candidate in Symbolic Systems: Human-Computer
>> Interaction (HCI)
>> Minor in Asian American Studies
>> Stanford University
>> Residential Computer Consultant (RCC) - Rains Z
>> BOSP Head Student Advisor
>>
>>
>> On Sun, Jan 11, 2015 at 4:41 AM, Jare Fagbemi <ofagbemi@stanford.edu
>> <javascript:_e(%7B%7D,'cvml','ofagbemi@stanford.edu');>> wrote:
>>
>>> Oh, okay, sorry, I misread the specific error. It was an issue with the
>>> collaborations. Fixed it now! I just forgot to set the groupNum attribute
>>> on the collab button.
>>>
>>> On Sun, Jan 11, 2015 at 6:41 PM, Jare Fagbemi <ofagbemi@stanford.edu
>>> <javascript:_e(%7B%7D,'cvml','ofagbemi@stanford.edu');>> wrote:
>>>
>>>> Got everything except for the handoffs problems now
>>>>
>>>> <Screen Shot 2015-01-11 at 6.30.23 PM.png>
>>>>
>>>> Changed the group icon to this and made it a tiny bit bigger.
>>>>
>>>> I'll look into the handoffs issue. I'm not getting any errors with
>>>> minimal testing, but I'll look over the code and try and test it a little
>>>> more very soon.
>>>>
>>>> On Sat, Jan 10, 2015 at 6:34 PM, A. To <notifications@github.com
>>>> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>>>>
>>>>> A couple comments:
>>>>> -I'm a little concerned because with some of the shorter events, there
>>>>> is almost no place where you can click to edit the events on the modal. Is
>>>>> it possible to have the modal open when you click on the title and the
>>>>> time? (Right now you get the text edit cursor hover)
>>>>> -I think the members icon can be a little larger. As of right now it
>>>>> is really hard to see what it is unless you look really closely. Or rather
>>>>> than larger, it just needs to be an icon that works well for that size.
>>>>> -Can you confirm that all of the appropriate json elements and globals
>>>>> have been changed? I'm seeing some errors with the rendering of the collabs
>>>>> and handoffs. Those may need to be fixed (I could do that), but if I
>>>>> recall, last time they were re-done they were using globals and values from
>>>>> the event json that made it so they would not need to be re-written if the
>>>>> event proportions changed. Specifically, I'm getting a "Cannot read
>>>>> property 'x' of undefined" when trying to draw some new collabs.
>>>>> -Finally, I don't know if the upload icon is firing the right thing.
>>>>> Check out the master branch. When I click upload there, it opens an alert
>>>>> that says "Team must be running to upload" and I don't get that on your
>>>>> branch.
>>>>>
>>>>> —
>>>>> Reply to this email directly or view it on GitHub
>>>>> <https://github.com/StanfordHCI/foundry/pull/172#issuecomment-69449881>
>>>>> .
>>>>>
>>>>
>>>>
>>>
>>
>
>

--

**Comment by ofagbemi** [comment]
Ok sounds good! I think for now if you can make the colors the way they were (grey by default, blue in progress, red delayed, green completed and yellow instead of grey if they are assigned to you) that would be a good temporary solution since this is something that should be fixed ASAP. Does that work for you? Let us know when to is fixed so we can merge my hiring portal branch :)

**Comment by ofagbemi** [comment]
Yes, exactly. I'll get to work on this as soon as I can, send you some
screenshots, and update the PR

On Monday, January 12, 2015, Daniela Retelny <dretelny@stanford.edu> wrote:

> Ok sounds good! I think for now if you can make the colors the way they
> were (grey by default, blue in progress, red delayed, green completed and
> yellow instead of grey if they are assigned to you) that would be a good
> temporary solution since this is something that should be fixed ASAP. Does
> that work for you? Let us know when to is fixed so we can merge my hiring
> portal branch :)
>
> Sent from my iPhone
>
> On Jan 11, 2015, at 3:43 PM, Jare Fagbemi <ofagbemi@stanford.edu
> <javascript:_e(%7B%7D,'cvml','ofagbemi@stanford.edu');>> wrote:
>
> Thanks! To Daniela, super sorry, I totally forgot to email you before I
> went to bedーI wanted to sync up with you again about the colors just to
> make sure everything was alright. I'm going to go back and adjust them this
> afternoon and hopefully I'll have something ready for you guys before your
> lunch time.
>
> On Monday, January 12, 2015, Daniela Retelny <dretelny@stanford.edu
> <javascript:_e(%7B%7D,'cvml','dretelny@stanford.edu');>> wrote:
>
>> Also, the events don’t appear to change colors once they are in progress,
>> completed, etc. Alexandra, were you aware of this?
>>
>> *Daniela Retelny*
>> Stanford University
>> Department of Management Science and Engineering
>> (914) 450-2033
>> dretelny@stanford.edu
>> www.danielaretelny.com
>>
>> On Jan 11, 2015, at 12:17 PM, Michael Bernstein <msb@cs.stanford.edu>
>> wrote:
>>
>> Hooray!
>>
>> On Sun, Jan 11, 2015 at 12:16 PM, Alexandra To <ato1120@stanford.edu>
>> wrote:
>>
>>> Really fantastic work! I just merged this, so everyone coding can pull
>>> the event redesign now!
>>>
>>>
>>>
>>> Alexandra To
>>> ---------------------------------------------------------------------
>>> B.S. '14, M.S. '15 Candidate in Symbolic Systems: Human-Computer
>>> Interaction (HCI)
>>> Minor in Asian American Studies
>>> Stanford University
>>> Residential Computer Consultant (RCC) - Rains Z
>>> BOSP Head Student Advisor
>>>
>>>
>>> On Sun, Jan 11, 2015 at 4:41 AM, Jare Fagbemi <ofagbemi@stanford.edu>
>>> wrote:
>>>
>>>> Oh, okay, sorry, I misread the specific error. It was an issue with the
>>>> collaborations. Fixed it now! I just forgot to set the groupNum attribute
>>>> on the collab button.
>>>>
>>>> On Sun, Jan 11, 2015 at 6:41 PM, Jare Fagbemi <ofagbemi@stanford.edu>
>>>> wrote:
>>>>
>>>>> Got everything except for the handoffs problems now
>>>>>
>>>>> <Screen Shot 2015-01-11 at 6.30.23 PM.png>
>>>>>
>>>>> Changed the group icon to this and made it a tiny bit bigger.
>>>>>
>>>>> I'll look into the handoffs issue. I'm not getting any errors with
>>>>> minimal testing, but I'll look over the code and try and test it a little
>>>>> more very soon.
>>>>>
>>>>> On Sat, Jan 10, 2015 at 6:34 PM, A. To <notifications@github.com>
>>>>> wrote:
>>>>>
>>>>>> A couple comments:
>>>>>> -I'm a little concerned because with some of the shorter events,
>>>>>> there is almost no place where you can click to edit the events on the
>>>>>> modal. Is it possible to have the modal open when you click on the title
>>>>>> and the time? (Right now you get the text edit cursor hover)
>>>>>> -I think the members icon can be a little larger. As of right now it
>>>>>> is really hard to see what it is unless you look really closely. Or rather
>>>>>> than larger, it just needs to be an icon that works well for that size.
>>>>>> -Can you confirm that all of the appropriate json elements and
>>>>>> globals have been changed? I'm seeing some errors with the rendering of the
>>>>>> collabs and handoffs. Those may need to be fixed (I could do that), but if
>>>>>> I recall, last time they were re-done they were using globals and values
>>>>>> from the event json that made it so they would not need to be re-written if
>>>>>> the event proportions changed. Specifically, I'm getting a "Cannot read
>>>>>> property 'x' of undefined" when trying to draw some new collabs.
>>>>>> -Finally, I don't know if the upload icon is firing the right thing.
>>>>>> Check out the master branch. When I click upload there, it opens an alert
>>>>>> that says "Team must be running to upload" and I don't get that on your
>>>>>> branch.
>>>>>>
>>>>>> —
>>>>>> Reply to this email directly or view it on GitHub
>>>>>> <https://github.com/StanfordHCI/foundry/pull/172#issuecomment-69449881>
>>>>>> .
>>>>>>
>>>>>
>>>>>
>>>>
>>>
>>
>>
>
> --
>
>

--

**Comment by ofagbemi** [comment]
Awesome, thanks so much!!!

**Comment by ofagbemi** [comment]
Alright, got some colors in

[image: Inline image 1]


Ignore the one in the top right.

Events that haven't been started look like this now

[image: Inline image 2]

I'll probably lighten up the icons a little bit.

Sorry for taking so long to get to this! Traffic was a little heavier than
I thought it'd be.

**Comment by ofagbemi** [comment]
Great! No worries. Others may have feedback about the colors, but I will
start testing functionality now!

Alexandra To
---------------------------------------------------------------------
B.S. '14, M.S. '15 Candidate in Symbolic Systems: Human-Computer
Interaction (HCI)
Minor in Asian American Studies
Stanford University
Residential Computer Consultant (RCC) - Rains Z
BOSP Head Student Advisor

**Comment by ofagbemi** [comment]
Can you re-issue a pull request?

Alexandra To
---------------------------------------------------------------------
B.S. '14, M.S. '15 Candidate in Symbolic Systems: Human-Computer
Interaction (HCI)
Minor in Asian American Studies
Stanford University
Residential Computer Consultant (RCC) - Rains Z
BOSP Head Student Advisor

**Comment by ofagbemi** [comment]
Went ahead and changed them again. I'll send in the PR now Alexandra!

[image: Inline image 1]

**Comment by ofagbemi** [comment]
Sent <https://github.com/StanfordHCI/foundry/pull/175>.

**Comment by ofagbemi** [comment]
Woohoo! This looks great!

**Pull request merged**
