### PR TITLE
Dr task modal

### PR DESCRIPTION
**Pull request by dretelny**
Updated the "read only" version of the modal to make it easier to read and interpret. 

When it is populated and before it is started: 
image

When a task has just been created (i.e. no information has been entered yet): 
image

When a task is in progress [note how the status text in the top right of the modal updates to in progress]: 
image

Completion modal where worker answers the documentation question (this is the same as before, no changes were made): 
image

When some questions have been answered but modal hasn't been submitted yet: 
image

When task has been completed (note how the status text in the top right changes to completed):
image

When testing: 
1) Make sure modals appear correctly in both worker and author view.
2) Test creating tasks with different amounts of information entered. Make sure none of the formatting is messed up when certain content is excluded. 
3) Check that the content makes sense / information flow looks good. 

For now, we decided that this is better then what is currently there. The next steps, however, include: (to be done in future PR): 
1) Update the inputs to list the previous tasks (using the dependencies/handoffs instead of manually entering inputs). These inputs/tasks will be links to their respective google drive folders. 
2) Potentially restructuring inputs and outputs -- TBD.

### CODE REVIEW

**Comment by negarrahmati** [comment]
The not started status jumps on the second row:
image

**Comment by negarrahmati** [comment]
Also, "Specifically, you are expected produce the following deliverables:" should be you are expected to  produce.

**Comment by negarrahmati** [comment]
One last thing! :) Can we change "You should review the following deliverables from previous tasks:" to "review the following deliverables from previous tasks:" ?

**Comment by dretelny** [comment]
Ok! Just made these changes. Can you pull and review again? 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Comment by dretelny** [comment]
Done! Pull and review :) 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Pull request merged**
