### PR TITLE
Show the documentation questions of the previous task

### PR DESCRIPTION
**Pull request by negarrahmati**
When the upcoming task of the worker is ready to get started, a modal pops up and shows the documentation questions of the previous task(s). If the page is opened after the task is ready to get started, the modal pops up right away. If there are multiple tasks with handoffs to the upcoming task, the worker can view the documentation questions by clicking next on the modal. The modal shows up only once for each worker and each upcoming task. 

This PR needs to be stress tested because I had to add an updateStatus() function in my code and that always worries me!

Create a team with at least two users. Create tasks that have two handoffs (depend on the completion of two tasks.) Refresh the page to make sure the modal shows up only once.

### CODE REVIEW

**Comment by dretelny** [comment]
It appears like if two people are assigned to the task, only one of them sees the documentation modal. I created a task with two workers assigned and then the previous task completed, only one of the two workers saw the documentation modal.

**Comment by negarrahmati** [comment]
Ok. I will check this.

**Comment by dretelny** [comment]
Also, before merging I think we should figure out some usability related things. For example, the worker should probably first see the workflow to see what they will be working on. They should also be shown the project overview, etc. In my opinion the documentation modals are a bit abrupt right now because they appear right away and then you can't get them back if you close them. Also, we might want a previous button for modals that have several screens.

**Comment by negarrahmati** [comment]
This is the new version of the previous PR based on the pilot results. 

When you click the start button on a task, a modal pops up indicating that you should read the documentation of the previous tasks first. If you click on OK, the documentation questions and the Gdrive link of the immediately previous tasks pop up in a new modal. If there are multiple previous tasks, you can click on previous/next buttons to brows through them. On the last modal, the start task button shows up to start the task. 

Please pay attention to the wordings of the modals. We probably need to modify them. 

Instructions to test:
Create a team with two task chains. Have at least three handoffs to a single task.
Add titles to all of the tasks. 
start the team. 
Start and complete the tasks one by one. 
When there are more than one immediately previous task, play with the next and previous buttons a few times before starting the task. (this is important)

Right now, this branch is on foundry-app-dev if you find it easier to test on heroku.

**Comment by dretelny** [comment]
Merging!

**Pull request merged**
