### PR TITLE
Task status in the sidebar.

### PR DESCRIPTION
**Pull request by negarrahmati**
This is how the status in the side bar works:
1. You are assigned to Mockups V1. ( This shows up when the previous task is not finished yet.)
2. You can start Mockups V1. (when all previous tasks are done and the current task is ready to start)
3. Your task is in progress.
4. Your task is delayed.
5. You have finished all your tasks! (When all tasks assigned the worker are finished.)

The status text has the same color code as the events. 

How to test:
Create a team with two different workers. Try to have long task names. Assign one worker to each task and check if the status is shown correctly. Refresh the page and check the status again.

### CODE REVIEW

**Comment by dretelny** [comment]
Before the project has started, it says the worker can start the task assigned to him/her. It should probably say the project hasn't started and notify them of which their next task is: 

image

**Comment by negarrahmati** [comment]
Good catch. I will fix it. Do you think the colors are ok?

**Comment by dretelny** [comment]
The yellow is a little hard to read but the other colors are fine! 

Also, see my comment on the PR again because I updated it with the other issues I found :) 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Comment by negarrahmati** [comment]
Ok :)

**Comment by negarrahmati** [comment]
@dretelny 
I fixed the first two bugs and upated the PR. 
I am not sure if your last comment is a bug. Based on the dependency chain Jay made, if we want the third task to start after the second task, we have to add the handoff. Otherwise, it means that the third task is not dependent on the second task and it makes more sense to assign a separate worker to it. What do you think?

**Pull request merged**
