### PR TITLE
Changed color palette

### PR DESCRIPTION
**Pull request by ofagbemi**
screen shot 2015-02-18 at 12 49 32 am

### CODE REVIEW

**Comment by ato1120** [comment]
Can you also update the colors on the color picker? 

screen shot 2015-02-17 at 11 36 44 am

**Comment by ofagbemi** [comment]
Finished. I think I'll probably try to sort the colors when I have time.

**Comment by ato1120** [comment]
Fantastic! I can do a little rudimentary sorting since I have the time now. You can clean it up later when you get a chance.

**Comment by ato1120** [comment]
Ok I sorted a little, but I realized now that when you change and save a member's color, the tabs on the timeline do not update. Can you add this?

**Comment by ofagbemi** [comment]
Okay, just fixed that, and I noticed the proper color wasn't selected in
the picker when you open the popover, so I fixed that too.

**Comment by ato1120** [comment]
Did you pull my changes before doing that? It looks like now the color selector went back to the old color palette...

**Comment by ofagbemi** [comment]
I thought I did, but I might've messed something upーI used GitHub's GUIS
version to do it.

On Thursday, February 19, 2015, A. To <notifications@github.com> wrote:

> Merged #243 <https://github.com/StanfordHCI/foundry/pull/243>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StanfordHCI/foundry/pull/243#event-237834474>.
>


--

**Pull request merged**
