### PR TITLE
Changed default task color

### PR DESCRIPTION
**Pull request by ofagbemi**
screen shot 2015-01-15 at 9 07 53 pm

### CODE REVIEW

**Comment by dretelny** [comment]
Let's wait on merging this until we decide what color we want. I'm not a big fan of the salmon. @ishitap is going to propose some colors too :)

**Comment by ishitap** [comment]
A quick idea - what about keeping the white boxes since it's so neutral but darkening the background graph to a light gray?

image

**Comment by dretelny** [comment]
that could work! would we want to change the background color of the page then? Feels weird to have both the page background and the row backgrounds be the same grey, right? 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Comment by ishitap** [comment]
Yeah, it looks weird when they are nearly the same color. The graph background gray could be more like the chatbox gray, maybe?

**Comment by ofagbemi** [comment]
Moved to #188

**Pull request closed without merging**
