### PR TITLE
Added folders to member menu

### PR DESCRIPTION
**Pull request by ofagbemi**
Users can categorize members into folders now. Right now ~~folders can't be deleted,~~ you can't change a folder's name, and you can't move members to another folder after you've created them. I'll send those changes in another pull request.

I'll change the look of a few things as soon as I get started on the full sidebar redesign.

screen shot 2015-02-11 at 2 47 39 am

screen shot 2015-02-09 at 12 15 19 pm

screen shot 2015-02-09 at 12 15 42 pm

screen shot 2015-02-09 at 12 15 33 pm

### CODE REVIEW

**Comment by ato1120** [comment]
Right now it looks like members who are not in a folder cannot be clicked on.

**Comment by ato1120** [comment]
From what I can tell, duplicated teams don't transfer any members - in the folder or not.

**Comment by ato1120** [comment]
I know this PR is quite large, but I don't think I can merge this until deleting is back at least. I will continue to look through it, but that is going to be critical, because otherwise if we merge this, if someone messes up during authoring, they will have to start all over with their team.

**Comment by ofagbemi** [comment]
Okay, fixed the root folder click issue. I'll add in folder deletion quickly. It shouldn't take too long.

**Comment by ofagbemi** [comment]
Added in folder deletion. A small x pops up on the side when the user
hovers over a folder. Members are still deleted via the popover.

PR's up here <https://github.com/StanfordHCI/foundry/pull/228>.

**Comment by ato1120** [comment]
There's a bug that does not exist on master where deleting a member leaves the popover still open and you can't close it.

**Comment by ato1120** [comment]
I also merged in the most recent master, so make sure to pull that.

**Comment by ato1120** [comment]
I think we also want to customize the delete alert window a little more for folder deleting. So instead of "remove member" as the button text, we want "remove member folder", etc.

**Comment by ato1120** [comment]
What will the search eventually do? Should it be doing something now? If not, that is fine, I just want to make sure I"m not missing anything.

**Comment by ofagbemi** [comment]
Sorry it's taken me a while to get on this. Fixed the popover bug and added
copy for the folder modal. Eventually the search box will pull up every
event it finds that contains the search string, no matter what folder it's
in. I haven't started implementing that yet.

Otherwise, I think the PR's ready. Let me know if you find anything else!

PR's up here <https://github.com/StanfordHCI/foundry/pull/228>.

**Comment by ato1120** [comment]
Ok, it looks like you fixed all the bugs but now there is another new one. =( 

If you open any team made *before* these changes, none of the roles appear in the list. Although they do still appear assigned to the tasks. The Team Roles number indicates 0 (Team Roles(0)) but if I add a new role, it will adjust to the correct number, but still not show the old members (i had 6, added 1, now says Team Roles (7)). 

To test this, try creating a team on master with team roles. Checkout your branch and open the team again. You will see that none of the roles appear. 

This is really great work and you're doing a great job addressing the things I find, it is just a large code base!

**Comment by ato1120** [comment]
Also be sure to check out the merge conflicts which it looks like we now have from the most recent updates.

**Comment by ofagbemi** [comment]
Okay, I made it backwards compatible now. Any team that gets loaded and
doesn't use the new system will automatically load its data into the right
place now. It won't work for the mixed teams that you might have now (where
you created some members without the changes and some members after the
changes), but it should work on everything else.

Let me know if you find anything else!

**Comment by ato1120** [comment]
This looks great! I am still seeing merge conflicts [note that we can't auto-merge this to master] so you might need to pull and update master again. 

There were a handful of small items folks at the meeting were hoping for before merging this: 
-Change 'root' to something more descriptive like "All Roles" so people can navigate a little easier
-Group folders and individuals separately (so all folders are at the top of the list and all individuals are below)

Finally, I noticed a small bug where if you create a folder within a folder, that second folder itself is counted as a member in the member tally.

**Comment by ato1120** [comment]
Agh, sorry, another bug. Now you can't add any roles or folders to new teams. 

On old teams, adding a folder will overwrite team roles starting with the first. 
On old teams you cannot add new team roles.

**Comment by ofagbemi** [comment]
Alright, fixed that bug, but just to make sure that there isn't a better
way to—where is flashTeamsJSON guaranteed to be loaded? It looks like it
happens in an AJAX call in awareness.js's renderEverything() function, but
it looks like some teams don't call it?

To the meeting stuff—I'll go ahead and add that in.

And to the member tally—do you mean the count of children in the folder
(the number in parentheses next to each folder)? That was supposed to count
the number of folders and members inside that folder. I realize now that
that's probably pretty confusing—I'll change it to the number of members
inside that folder.

**Comment by ofagbemi** [comment]
Alright, added everything now. Let me know if you find anything else!

**Comment by ato1120** [comment]
I don't think anything is clickable now. I can't draw any events on the timeline and I can't expand the team roles to add anyone. 

From the console error, it looks like some '<<' chars were left behind?

**Comment by ofagbemi** [comment]
Haha this has been a struggle. I realized I forgot to push! Should be good
now.

**Comment by ato1120** [comment]
This looks fantastic!! Nice work!

**Pull request merged**
