### PR TITLE
Layered timeline

### LINKED ISSUE #176: You can't click on handoffs or collaborations
It appears like you can only click on the latest one that was created. There is no way to make the popover appear on most of them (the mouse also doesn't change to a pointer unless you can click on it, which is with very few). This appears to be a new bug since introducing the new event blocks

### PR DESCRIPTION
**Pull request by ofagbemi**
Fixes #176

Keep the timeline's pieces in distinct layers now:
1. Grid layer
2. Selection layer
3. Event layer
4. Handoff layer
5. Collaboration layer

These layers' root SVG elements are all accessible via the `window._foundry.timeline` object. Continue to add listeners for the entire timeline to `window._foundry.timeline.timelineSvg` (the mousemove listener for drawing handoffs, for example, is attached to this element).

screen shot 2015-01-23 at 8 44 02 pm

### CODE REVIEW

**Comment by ato1120** [comment]
This is great work! It seems to have fixed all of the issues with the handoffs and collaborations. However, it still seems inconsistent with the members on events. The pattern I'm seeing is: 
-Hover will always show the names on the first event in the json.
-Hover will not show any names on events that are third [2] or later in the json. 
-Hover will inconsistently show names on the second event in the json (sometimes just the last member on the event, sometimes more). 

This is exactly the same on the master branch. I might be misidentifying the pattern, but the hovering for names is definitely not working for every event.

**Comment by ato1120** [comment]
I'm also seeing a bug with event deleting. The following error fires in the console from awareness.js 
Uncaught TypeError: Cannot read property 'groupNum' of undefined

Drawing a new event will also sometimes make an old event disappear. I thought this bug was in master but I can't get it to replicate there, only on this branch.

**Comment by ofagbemi** [comment]
Alright, fixed everything except the old event disappearing bug. It turned
out the tooltip stuff was unrelated. When I was setting up the tooltip on
the member tabs (Bootstrap requires you to call a "tooltip" function on
every tooltip enabled element), I was using an id "#" selector, so it'd
only grab the first element in the DOM with that id. I switched over to
using a different selector.

**Comment by ato1120** [comment]
Nice work! 

Yeah, that bug is actually on master. Given that this branch is not introducing it, I think I am going to merge it. But is that something you'd be willing to look into? I'm going to file an issue and tag you since it is timeline related.

**Comment by ato1120** [comment]
Actually, that is definitely related to the 'same id' but you already filed. Add screenshots there.

**Pull request merged**
