### PR TITLE
Dr pause event

### PR DESCRIPTION
**Pull request by dretelny**
This PR adds the ability to pause tasks. Below is how it works: 

1) I added a pause button to the modal. The pause button appears after you start a task: 
image

2) If you click on pause, four things happen:

a) the pause button changes to a resume button and the complete button is hidden: 
image

b) the timer on the task block is paused

c) the text on the sidebar in worker view says "Your task is paused" (in the dark blue color):
image

d) the task blocks turn a darker blue/grey. In author view, they are darker (opacity = 1). In worker view, they are more blueish/greyish (same color as author view but opacity = .6). Below are screenshots of blocks in author view and worker view: 

author view: 
image

worker view: 
image

3) When you click on the "resume task" button in the modal, the task should change back to the color it was before (either blue if in_progress -but not delayed- or red if delayed). The button in the modal should switch to "pause" and the complete button should reappear next to the pause button. 

Now for the important things to pay attention to: 
While the feature appears to be "simple," it required making a few big changes across several files. Please make sure to "compare" the files in github (i.e. the side by side comparison view in the PR). Below is a summary of the big changes: 

1) I changed how we calculate the remaining task. Previously we would subtract the time the task was started from the current time but this no longer worked when tasks were being started, paused and resumed. Instead, I created two new variables that are saved in the event object. The first one is "task_latest_active_time" which is a timestamp that is updated when the task is started, paused and resumed. I then use this variable instead of the start task time variable to calculate the "time_passed." The second variable I introduced is "latest_remaining_time" which saves the value of the timer. I then use this to update the timer in the drawTimer function in events.js. Specifically, i subtract time_passed from latest_remaining time to calculate the time shown on the timer on the task block. When testing, please make sure that this logic makes sense and that the time is right (both when task is in progress and delayed). 

2)  I created a new array called paused_tasks which is used to construct the status object and in a few other places, which are critical for updating the different views. Specifically, this array (in conjunction with the live_tasks and remaining_tasks arrays) is used in the constructStatusObj, flashTeamUpdated, loadData functions in awareness.js, all of which are critical for making sure the views are updated properly (this took me quite a while to figure out). For now, if a pause is tasked, I add it to the paused_task array but also leave it in the live_task array (or the delayed_task array). I thought it was riskier to remove it and couldn't think of a reason to remove it but let me know if you disagree. 

When testing, do the following: 
1) Create a new team with a bunch of tasks and handoffs 
2) Add member(s) to some of the tasks 
3) Start the team and invite the member(s) --> open the project in both author and worker view
4) Start a task in worker view
5) Pause the task in worker view and make sure it updates in author view as well. Also make sure the sidebar in worker view says "your task is in progress." Finally, make sure that the timer is paused. 
6) Resume the task, make sure it updates in author view and that the sidebar in worker view updates to the task is in progress (if the task was delayed when you paused it, it should say the task is delayed). More importantly, make sure that the timer resumes where it left off. 
7) Let a task get delayed, pause it, resume it. Make sure all is ok. 
8) If possible, we might want to check the emails and make sure the delayed emails are sent properly if a task is paused but this is less important right now. 

Feel free to test other things I might have forgotten. Also, one point to keep in mind for the future has to do with the colors. Right now, paused tasks regardless of whether they are delayed or not are the same color. I'm not sure if we want to distinguish that in anyway. The colors are easy to change though :) 

Thanks!!!

### CODE REVIEW

**Comment by negarrahmati** [comment]
Nice job! I couldn't catch a single bug! :dart: :dancer: 

I am just wondering if we need to add some thing (besides the dark blue color) to the paused events so that other workers can realize a task is delayed. Maybe we can add a tiny pause button near the timer of the paused event? I can merge this and add a git issue.

Let me know what you think! :] @dretelny

**Comment by dretelny** [comment]
That works!! Thanks!!

**Comment by dretelny** [comment]
Let me know when this is merged so I can update the herokus!

**Comment by negarrahmati** [comment]
Could you merge it yourself? I have already tested it and it is working
perfectly.

Thanks!

**Comment by dretelny** [comment]
oh ok! yep, I’ll merge it! Thanks! 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Pull request merged**
