### PR TITLE
Event redesign pt. 2

### PR DESCRIPTION
**Pull request by ofagbemi**
Colors:

screen shot 2015-01-12 at 3 38 44 pm

screen shot 2015-01-12 at 3 34 20 pm

### CODE REVIEW

**Comment by ato1120** [comment]
It doesn't look like the timer is working. Or at least the minutes are not counting down on the events anymore!!

**Comment by ato1120** [comment]
My tasks are also not highlighted yellow. This is logged in as the orange UI Designer
screen shot 2015-01-11 at 10 42 56 pm

**Comment by ofagbemi** [comment]
Just checking, is each minute on the timeline supposed to correspond to one
second? If so, then I fixed the timer issue. I'll move on to the worker
view.

**Comment by ofagbemi** [comment]
*one second in real life?

**Comment by ofagbemi** [comment]
Actually, Alexandra, I think you might be looking at an outdated branch.
The event colors should be white, not blue. In my worker view, they're
white.

I'm a little hazy on when exactly the tasks should be yellow. Did they
already turn yellow, and my PR broke that? Or are you asking me to
implement it. Sorry for the confusion!

**Comment by ato1120** [comment]
I just pulled the new set. Looks great! When you log on as a worker, your tasks should all be yellow *before* they are started. They align with the rest of the color sets otherwise. Yes, they were yellow in the last version of master.

**Comment by ofagbemi** [comment]
Alright fixed. One more question—what does the lowered opacity signify
again?

**Comment by ato1120** [comment]
As I recall, the intention is that your first task is full opacity and subsequent tasks are low opacity.

**Comment by ato1120** [comment]
I wouldn't be concerned with that if it is not working. The events look great!

**Comment by ato1120** [comment]
Should I merge this when I'm done checking or do you want to fix anything with the opacity?

**Comment by ofagbemi** [comment]
You can go ahead and merge it in. I'll probably add some clean up stuff
later, but it might take a while, as might working with the opacity stuff.

**Pull request merged**
