### PR TITLE
Kartik hiring

### PR DESCRIPTION
**Pull request by sawhney-kartik**
Implemented the dynamic hiring status feature. Here are the details:

1. Created a separate table called Landing that keeps track of a number of features to monitor the user on the landing page. 
2. The task available email that is sent to every person contains a custom landing URL that has the email address of the user. This helps identify a user. 
3. if the user is first in the hiring queue, he is automatically redirected to the "task acceptance" page, where he gets 10 minutes to read about the project and completing the entire registration process (including confirming his/her email address). This page refreshes after 600 s (10 minutes) because the user might have lost his first position in the queue.
4. If not, a separate page is displayed which contains realtime hiring status (the amount of time that the person should wait). To ensure that the person is not just staring at the screen during that time, the content that he will have to read later is also displayed. 

Testing

1. The database will have to be migrated first because of the addition of a table. 
2. Here are a few scenarios to test. 
i. No person in the queue, task acceptance, the first user completes the registration process, second person comes, task unavailable should be displayed
ii. No person in the queue, task acceptance, the first user does not complete the registration process in 10 Mins., second person comes, task available should be displayed, the first user tries again, he should no longer be 1st in the queue now
iii. Two concurrent users

### CODE REVIEW

**Comment by dretelny** [comment]
1) The "I accept" URL in the email doesn't work but it works on the email confirmation page (e.g., when you click on the send task available email and the page loads confirming you sent the email, the link works there). Specifically, the link that gets sent in the actual email received by the worker is: http://landings/1/1/view?task_member=UX&email=dretelny@stanford.edu,%20daniela.retelny@gmail.com

2) The URL appears to have all of the emails of all panel members in it, which doesn't seem like what should happen. However, I don't know if this always happens since I can't click on the link in the email (so  the link I used is the one that appears on the confirmation page). Specifically, if I go to the page using the link with all of the emails, it takes a stop in the queue and then if I erase all of the emails except for the first one it adds that person to the queue again since it thinks it is a separate email. 

3) The timer on the page for the person at the top of the list (e.g., No. 1) always says 10 minutes even if you refresh. This should count down like the others. Also, after 10 minutes on the No. 1 page, the page never refreshed (likely due to the same problem). Once I refreshed the page, it told me I was No. 4 in the queue. 

4) If I close the page, the person remains in the queue. 

5) If I remove the email parameter (and email word) from the URL, it still adds someone to the queue. 

6) I can enter any email into the URL and it will add to the queue.

**Comment by sawhney-kartik** [comment]
Fixed all the issues. Tested it on Heroku, and it seems to work for me (the most recent version is pushed to Heroku).

**Comment by dretelny** [comment]
When you accept a task on Foundry, it asks you to use the same email you used when you sign up. If you sign up with a different email, it lets you sign up but then the hiring portal never updates the queue to let them know that the job is no longer available. It does work if you use the correct email though. I wonder if we should not let the person accept the job if the email doesn't match? Or update the portal when the job has been accepted regardless. What do you think? It's probably best to make sure the email matches in case the worker enters a typo or something.

**Comment by dretelny** [comment]
One other question: is there a reason, it only refreshes every 120 seconds? Would it be difficult (and/or inefficient) to refresh more frequently?

**Comment by sawhney-kartik** [comment]
1. The page for the first person in the queue now refreshes every 60 s instead of 120 s. 
2. An error is generated if the email address entered in the form does not match our records (so, the email address that a person enters on this form has to be the same as the one that he/she used for registration). 
3. I purposely do not remove the person from the queue if he closes the page. This is because there is a possibility that the person might leave the page to complete the registration process (say, to confirm his email). I think, it's okay to have others wait a little longer, than remove a person from the queue simply because the page closed for some reason. Of course, if the person actually is no longer interested, he can always click that link. Maybe, we could make that link more prominent so that people know what to do if they are not interested. Thoughts? I was thinking about a confirmation that pops up when the person tries to close a page, saying that he must either accept the position (if he is No. 1 in the queue) or remove himself from the queue. However, unfortunately, since the page is refreshed every 60 s, the browser considers it to be an "unload" event, resulting in that message. So, I'm not sure how I could implement this feature.

**Comment by sawhney-kartik** [comment]
If email specified while accepting task does not match our records, error is displayed on the same form page, rather than a separate page.

**Comment by sawhney-kartik** [comment]
Added a confirmation message before the user is removed. Also, fixed the bug in the hiring queue.

**Comment by dretelny** [comment]
Thanks Kartik! I will try to take a look soon. Quick question/request, would it be possible for you to change the layout used for workers so that the sidebar with the links to the emails, queue, etc. does not show up? I think it is easiest to just have a conditional somewhere that is used when choosing the layout. Let me know if this is something you can do. We definitely shouldn't merge it until this happens since workers shouldn't have access the emails, queue, etc. Thanks!

**Comment by sawhney-kartik** [comment]
Changed the layout such that all of the information like hiring E-mails and queue etc. is no longer displayed.

**Comment by dretelny** [comment]
This looks good! I think it is ready to merge once we fix some of the design issues :) Thanks, Kartik!

**Comment by dretelny** [comment]
I updated this branch with some design changes, described below. First, I want to include the testing instructions. 

TESTING INSTRUCTIONS: 
1) Migrate your database! 
2) Create an account and a team (since your database will now be empty)
3) Add roles / tasks
4) Click the hire button for one of the tasks and send the task available email to 2-3 people (you either need to add people to your panels or just enter their email addresses manually)
5) Check the text in the email and make sure it looks ok
6) Click on the "i accept" link in one of the emails, it should take you to the task available landing page and tell you that you are number 1 in the queue. you should see the accept / decline buttons
7) Keep the queue page open but go back and click on the "i accept" link in one of the other emails (open the link in a different tab), the landing page should tell you that you are number 2 in the queue 
8) Accept the task on the page with the number 1 queue position, fill out the registration form and click on the foundry project link emailed to you
9) Within ~60 seconds, the page with the other queue (where you were number 2) should refresh and tell you the task is no longer available 
 
UPDATES:
**Add spot in queue, time left to the sidebar in worker view:** DONE (still need to improve design but the content is there)
- the left sidebar now includes the position in queue as well as action buttons (see screenshots in the bullet point below)

**Add opt out and accept buttons to the sidebar in worker view:** DONE (design can be improved)
- Specifically, if you are number 1 in the queue, you will see accept and decline buttons: 

image

- If you are in the "waiting queue" (e.g., not number 1), you will see a decline link: 
image

- If the task is unavailable, you just see the project and task name

**Hiring queue and task available email links are both “active” in author view at same time:** FIXED/DONE
- the task available email and the hiring queue links in the left sidebar are now "active" when they should be (only one should be active at any given time, previously they were both active)

**Hiring queue link doesn't appear in the sidebar when you select a role and view the queue:** FIXED/DONE
- the hiring queue link now appears in the left sidebar when viewing the queue page

**The hiring queue link is not active on the hiring queue page (before you select a role):** FIXED/DONE
- as mentioned above, the hiring queue link now appears in the left sidebar when viewing the queue page

**Remove “task available email sent” header from email:** DONE
- Previously, when you sent the task available email, you would see a header confirming that the email was sent. This header would also be included in the email sent to the workers since it uses the same code. Therefore, I revised the confirmation text to be more generalizable. The image below shows what it now says/looks like: 
image

**Review / revise text on both queue pages (# 1 and others) and the task available emails:**  SORT OF DONE, we should take another pass
- I started to revise the text on the page to make things clearer, although we should probably take another pass at some point. 
- I also updated the design / layout of the text to try and break some of the text up a bit and emphasize the different sections / type of content on the page (queue number/wait time, instructions, task information, etc.

**Comment by ato1120** [comment]
It looks like right now the hiring page has an automatically filled in portion for the project overview, task description, and deliverables, but the email sender has a manual fill-in. This could potentially lead to conflicting task descriptions. I will file this as its own bug. 

MAJOR bug scenario: 
In the queue, Person A is in spot no. 1 and Person B is in spot no. 2. 
Person A clicks "I accept this role" and is redirected to a form to submit their email. 
Person A submits their name and email. 
An email arrives to Person A including their unique link to Foundry. They do NOT open this email or click the link. 
The original 10 minutes for Person A runs out.
Person B is bumped to spot no. 1
Person B clicks "I accept this role"
BUG: Person B is directly linked to Person A's unique link on Foundry. Now both Person A and Person B have access to the same Foundry account.

**Comment by ato1120** [comment]
It looks like right now the hiring page has an automatically filled in portion for the project overview, task description, and deliverables, but the email sender has a manual fill-in. This could potentially lead to conflicting task descriptions. I will file this as its own bug. 

MAJOR bug scenario: 
In the queue, Person A is in spot no. 1 and Person B is in spot no. 2. 
Person A clicks "I accept this role" and is redirected to a form to submit their email. 
Person A submits their name and email. 
An email arrives to Person A including their unique link to Foundry. They do NOT open this email or click the link. 
The original 10 minutes for Person A runs out.
Person B is bumped to spot no. 1
Person B clicks "I accept this role"
BUG: Person B is directly linked to Person A's unique link on Foundry. Now both Person A and Person B have access to the same Foundry account.

**Comment by ato1120** [comment]
It looks like right now the hiring page has an automatically filled in portion for the project overview, task description, and deliverables, but the email sender has a manual fill-in. This could potentially lead to conflicting task descriptions. I will file this as its own bug. 

MAJOR bug scenario: 
In the queue, Person A is in spot no. 1 and Person B is in spot no. 2. 
Person A clicks "I accept this role" and is redirected to a form to submit their email. 
Person A submits their name and email. 
An email arrives to Person A including their unique link to Foundry. They do NOT open this email or click the link. 
The original 10 minutes for Person A runs out.
Person B is bumped to spot no. 1
Person B clicks "I accept this role"
BUG: Person B is directly linked to Person A's unique link on Foundry. Now both Person A and Person B have access to the same Foundry account.

**Comment by sawhney-kartik** [comment]
Fixed the second bug regarding both users getting the same email confirmation links. 

Regarding the first bug, I have a question. Is there an easy way for the PC (or whoever created the task) to change the task details, such as description etc.? If so, we can make all fields except "to", "from", "subject" and "task member" as read-only on the form, so that there is no disparity. To edit the task, the PC will necessarily have to change the task details (which I'm assuming will change the json), and hence those changes will also be reflected in the hiring portal. Passing all the info as parameters to the hiring portal seems to be very inefficient.

Testing for bug2 fix:

1. Send the invitation to 2-3 email addresses. 
2. The first user at position No. 1 enters the details, receives the confirmation email, but does not click the URL to confirm the email address. 
3. The user at No. 1 runs out of time, and then user No. 2 gets the confirmation email. 
4. Try user No. 1's confirmation email URL. An error to the effect of time running out should be displayed. Confirmation URL for user No. 2 should work. 

The most recent code is up on Heroku as well.

**Comment by ato1120** [comment]
Thanks for getting to this so quickly! @dretelny, if you can push this to the heroku for testing I can check out the fix for bug 2. Daniela, do you have suggestions for bug 1? Everything else on the PR looked good to me.

**Comment by sawhney-kartik** [comment]
Pushed the most recent code to Heroku for testing

**Comment by ato1120** [comment]
Really nice job on this! Looks good to me. I'm ready to merge if we want to file the other bug to fix later. I don't think it's critical since we should rarely have people with blank project descriptions, etc.

**Pull request merged**
